<template>
    <div class="signin-background">
      <div class="signin-container">
        <h1 class="title">Team Code</h1>
        <p class="subtitle">Enter the Team Code generated by your coach</p>
  
     
        <div class="role-container">
          <div class="role-box">
            <div class="role-image">
          
              <img src="./player.png" alt="Player" />
            </div>
          </div>
        </div>
  
        <!-- Team Code Input Box -->
        <input type="text" class="team-code-input" placeholder="Team Code" />
  
        <!-- Sign Up Button -->
        <RouterLink to="/team" class="login-button">SIGN UP</RouterLink>
  
        <!-- Back Text -->
        <RouterLink class="create-account" to="/who">BACK</RouterLink>
      </div>
    </div>
  </template>
  
  <style scoped>
  html, body {
    background: linear-gradient(185deg, rgb(34, 32, 32) 80%, red 80%);
    height: 100%;
    margin: 0;
    padding: 0;
    height: 100vh;
  }
  
  .signin-background {
    display: flex;
    justify-content: center;
    align-items: center;
  }
  
  .signin-container {
    font-family: 'Roboto';
    display: flex;
    flex-direction: column;
    justify-content: flex-start;
    align-items: center;
    width: 100%;
    max-width: 750px;
    text-align: center;
    padding: 20px 20px;
    box-sizing: border-box;
    height: 100%;
    max-height: 100vh;
    margin-top: 2%;
  }
  
  .title {
    font-size: 2rem;
    font-weight: 700;
    color: white;
    margin-top: 0;
  }
  
  .subtitle {
    font-size: 0.9rem;
    font-weight: 400;
    color: white;
    margin-top: 5px;
  }
  
  /* Login Button */
  .login-button {
    width: 100%;
    max-width: 700px;
    height: 50px;
    background-color: #FF5448;
    color: white;
    font-size: 1.2rem;
    font-weight: 700;
    border: none;
    border-radius: 13px;
    margin-top: -25px;
    cursor: pointer;
    display: flex;
    justify-content: center;
    align-items: center;
    text-decoration: none;
  }
  
  .login-button:hover {
    background-color: #FF3B32;
  }
  
  .router-link-active {
    text-decoration: none;
  }
  
  .create-account {
    font-size: 1.6rem;
    color: white;
    font-weight: 500;
    text-decoration: none;
    margin-top: 25px;
    transition: all 0.3s ease;
  }
  
  .create-account:hover {
    transform: scale(1.05);
  }
  
  .role-container {
    display: flex;
    justify-content: center;
    width: 100%;
    margin-top: 30px;
  }
  
  .role-box {
    width: 170px;
    height: 170px;
    border: 3px solid #FF5448; 
    border-radius: 10%;
    background-color: transparent;
    color: white;
    display: flex;
    justify-content: center;
    align-items: center;
    font-size: 1.5rem;
    font-weight: bold;
    text-align: center;
    position: relative;
  }
  
  .role-image {
    position: absolute;
    top: 25px; 
    width: 115px;
    height: 115px;
    border-radius: 50%;
  }
  
  .role-image img {
    width: 100%;
    height: 100%;
    object-fit: contain; 
  }
  
  .team-code-input {
    width: 100%;
    max-width: 700px;
    padding: 12px;
    margin: 55px 0;
    border-radius: 13px;
    border: 1px solid #ccc;
    background-color: white;
    color: #333;
    font-size: 1.1rem;
    text-align: left;
  }
  
  .team-code-input::placeholder {
    color: #aaa;
    font-weight: 400;
  }
  </style>
  